/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppPriorityRouteImport } from './routes/app.priority'
import { Route as AppPredictionRouteImport } from './routes/app.prediction'
import { Route as AppDiagnosisRouteImport } from './routes/app.diagnosis'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPriorityRoute = AppPriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionRoute = AppPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosisRoute = AppDiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/diagnosis': typeof AppDiagnosisRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/priority': typeof AppPriorityRoute
  '/app/report': typeof AppReportRoute
  '/app/risk': typeof AppRiskRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/diagnosis': typeof AppDiagnosisRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/priority': typeof AppPriorityRoute
  '/app/report': typeof AppReportRoute
  '/app/risk': typeof AppRiskRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/diagnosis': typeof AppDiagnosisRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/priority': typeof AppPriorityRoute
  '/app/report': typeof AppReportRoute
  '/app/risk': typeof AppRiskRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/diagnosis'
    | '/app/prediction'
    | '/app/priority'
    | '/app/report'
    | '/app/risk'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/assistant'
    | '/app/diagnosis'
    | '/app/prediction'
    | '/app/priority'
    | '/app/report'
    | '/app/risk'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/diagnosis'
    | '/app/prediction'
    | '/app/priority'
    | '/app/report'
    | '/app/risk'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/priority': {
      id: '/app/priority'
      path: '/priority'
      fullPath: '/app/priority'
      preLoaderRoute: typeof AppPriorityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prediction': {
      id: '/app/prediction'
      path: '/prediction'
      fullPath: '/app/prediction'
      preLoaderRoute: typeof AppPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnosis': {
      id: '/app/diagnosis'
      path: '/diagnosis'
      fullPath: '/app/diagnosis'
      preLoaderRoute: typeof AppDiagnosisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppDiagnosisRoute: typeof AppDiagnosisRoute
  AppPredictionRoute: typeof AppPredictionRoute
  AppPriorityRoute: typeof AppPriorityRoute
  AppReportRoute: typeof AppReportRoute
  AppRiskRoute: typeof AppRiskRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppDiagnosisRoute: AppDiagnosisRoute,
  AppPredictionRoute: AppPredictionRoute,
  AppPriorityRoute: AppPriorityRoute,
  AppReportRoute: AppReportRoute,
  AppRiskRoute: AppRiskRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
